name: Check with pylint

on:
  push:
  
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pylint
        run: pip install pylint
      - name: Run tests
        run: pyton -m unittest discover tests
      - name: Analyze code with pylint 
        run: pylint shopping_cart.py tests/
      